### ISSUE TITLE
BLTouch Not deploying at print start _ Creality Dwin2.0

### ISSUE THREAD

**Issue by antoinelb1** [InsanityAutomation/Marlin#141] opened 2020-05-16 00:40 UTC
Hi, I have a Ceality Ender 5 Plus and am trying to have it run with an SKR PRO V1.1 board. 
I have successfully built and loaded CrealityDwin_2.0 and con controll all my axis.
I have the BLtouch that came with the Creality printer.  (v3.1)
I have re-loaded and re-built with the most recent file last week. 

When connected to the board, if i send a G28 or G29 command through  Pronterface or Octopi, the printer operates properly and does level/mesh(4x4) without any issue ! The BLTouch does probe whenever needed and seem repeatable from the result i got.

I have succesfully leveling my bed using Octopi/ Pronterface
I have adjusted my Z and using the touchscreen z up/down like i had to do on the default creality board and should be ready to print.  

My "main" issue is that when i send a print request ( through cura or octopi ), It heats the bed and nozzle properly, home x and y, then move to the center of the bed  and starts moving the bed up without having the BLtouch deployed!!! The nozzle then crashes into the bed... D: 

I have also some issue with the leveling button on the touchscreen that might be related to that one... 
-Twice the leveling button did not deploy the BLTouch ( out or over 100 try ).
-The meshing button seems to send something else than G29 as it start heating my bed and nozzle, then home x,y and crashes into the bed, like it does at a print start...

I'm having a hard time figuring out whats wrong.
Has anyone had this issue before ?
Am i configuring something wrong ?
Can anybody help ? i can provide any detail you may need to help me ! 

Start G-Code ( in Cura) : 
_G28 ;Home
M201 X500.00 Y500.00 Z100.00 E5000.00 ;Setup machine max acceleration
M203 X500.00 Y500.00 Z10.00 E50.00 ;Setup machine max feedrate
M204 P500.00 R1000.00 T500.00 ;Setup Print/Retract/Travel acceleration
M205 X8.00 Y8.00 Z0.40 E5.00 ;Setup Jerk
M220 S100 ;Reset Feedrate
M221 S100 ;Reset Flowrate
G92 E0 ;Reset Extruder
G1 Z2.0 F3000 ;Move Z Axis up
G1 X10.1 Y20 Z0.28 F5000.0 ;Move to start position
G1 X10.1 Y200.0 Z0.28 F1500.0 E15 ;Draw the first line
G1 X10.4 Y200.0 Z0.28 F5000.0 ;Move to side a little
G1 X10.4 Y20 Z0.28 F1500.0 E30 ;Draw the second line
G92 E0 ;Reset Extruder
G1 Z2.0 F3000 ;Move Z Axis up_

Octoprint G-Code Terminal of a print start :

Recv:  T:199.97 /200.00 B:60.16 /60.00 @:61 B@:0
Recv: Not SD printing
Recv: wait
Recv: Not SD printing
Recv: wait
Recv:  T:199.97 /200.00 B:60.15 /60.00 @:61 B@:0
Recv: Not SD printing
Changing monitoring state from "Operational" to "Printing"
Recv: wait
Send: N0 M110 N0*125
Recv: ok N0 P15 B7
Send: N1 M140 S50*81
Recv: ok N1 P15 B7
Send: N2 M105*37
Send: N3 M190 S50*94
Recv: ok T:200.00 /200.00 B:60.17 /50.00 @:60 B@:0
Send: N4 M104 S200*99
Recv: ==onPrintTimerStarted==
Recv: //action:notification Bed Cooling...
Recv: //action:notification Printing...
Recv: ok N3 P15 B7
Send: N5 M105*34
Recv: ==onConfigurationStoreWritten==
Recv: ok N4 P15 B7
Send: N6 M109 S200*108
Recv: Not SD printing
Recv: ok T:200.00 /200.00 B:60.17 /50.00 @:60 B@:0
Send: N7 M82*30
Recv: ==onPrintTimerStarted==
Recv:  T:200.00 /200.00 B:60.17 /50.00 @:60 B@:0 W:?
Recv:  T:199.91 /200.00 B:60.24 /50.00 @:62 B@:0
Recv: Not SD printing
Recv:  T:199.89 /200.00 B:60.13 /50.00 @:62 B@:0 W:2
Recv: echo:busy: processing
Recv: Not SD printing
Recv:  T:199.83 /200.00 B:60.11 /50.00 @:63 B@:0 W:1
Recv:  T:199.66 /200.00 B:60.14 /50.00 @:66 B@:0
Recv: Not SD printing
Recv:  T:199.66 /200.00 B:60.14 /50.00 @:66 B@:0 W:0
Recv: //action:notification Printing...
Recv: ok N6 P15 B6
Send: N8 G28*27 
Recv: Not SD printing
Recv: ok N7 P15 B7
Send: N9 M201 X500.00 Y500.00 Z100.00 E5000.00*3
Recv:  T:199.49 /200.00 B:59.99 /50.00 @:67 B@:0
Recv: Not SD printing
Recv: echo:busy: processing
Recv: Not SD printing
Recv:  T:199.43 /200.00 B:59.99 /50.00 @:67 B@:0
Recv: Not SD printing
Recv: echo:busy: processing
Recv: Not SD printing
Recv:  T:199.29 /200.00 B:59.98 /50.00 @:69 B@:0
Recv: Not SD printing
Recv: echo:busy: processing
Recv: Not SD printing
Recv:  T:199.46 /200.00 B:59.87 /50.00 @:66 B@:0
Recv: Not SD printing
Recv: echo:busy: processing
Recv:  T:199.52 /200.00 B:59.82 /50.00 @:66 B@:0
Recv: Not SD printing
Recv: Not SD printing
      
As you can read above, it seems like the printer is receiving the G28 command (N7 M82*30 and N8 G28*27) but im not sure what the *27 and *30 are.

**Comment by masc2279** [comment] 2020-05-26 14:01
First run M503 and see if your auto level is truly set. G29 is doing the auto level as you stated but at no point have you said after the G29 you saved the mesh using an M500.

So run a M503 and see if the mesh is there if not using an M28 will blow out any temp mesh that was being stored but not saved causing your issue

Personally in all my start scripts after G28  i run a G29  and then an M500 which auto levels during every start of print.

Also you have not said if you are setting your Z offset after auto level which also causes the crashing issue if the wrong Z value is set.

so turn off your printer turn it back on and run a M503 and post here if you want more help

And yes i have seen this issue when auto level was not fully configured but its been a long while

**Comment by masc2279** [comment] 2020-06-03 23:59
I dont see any auto leveling on your console at all  here is the section showing from my setup.

Run your auto level and then right after send an M500 to save it then re run the M503 you should see an auto level section and the data from the auto level once properly configured and saved.

<img width="858" alt="Screen Shot 2020-06-03 at 5 56 57 PM" src="https://user-images.githubusercontent.com/1273722/83700309-b14c6100-a5c3-11ea-8ab4-8826d4e7e443.png">

**Comment by antoinelb1** [comment] 2020-06-07 21:39
Hi there, thanks for the feedback !

I had not M500 before but the data from the meshing seemed to be stored somewhere as it is reflected in the Creality Default touchscreen. (have to home with the front screen before running G29 to be on the proper display)

I believe your porbably that your right, it could very well be related to the meshing not being properly stored but am totatly wonreing why it would prevent the BLTouch to get deplayed during my print start GCode. 

Masc2279, I agree, i should ideally run G28,G29 and M500 at my print start but my current issue is that i sadly can't go through the G28 command without crashing the nozzle into the bed.

As per your recommendation, I have now ran M28, M29 followed by M500.

The results when i run M503 are the following : 

Send: M503
Recv: wait
Recv: echo:  G21    ; Units in mm (mm)
Recv: 
Recv: echo:; Filament settings: Disabled
Recv: echo:  M200 D1.75
Recv: echo:  M200 D0
Recv: echo:; Steps per unit:
Recv: echo: M92 X80.00 Y80.00 Z800.00 E95.00
Recv: echo:; Maximum feedrates (units/s):
Recv: echo:  M203 X750.00 Y750.00 Z10.00 E75.00
Recv: echo:; Maximum Acceleration (units/s2):
Recv: echo:  M201 X2000.00 Y2000.00 Z100.00 E75.00
Recv: echo:; Acceleration (units/s2): P<print_accel> R<retract_accel> T<travel_accel>
Recv: echo:  M204 P750.00 R1000.00 T300.00
Recv: echo:; Advanced: B<min_segment_time_us> S<min_feedrate> T<min_travel_feedrate> J<junc_dev>
Recv: echo:  M205 B20000.00 S0.00 T0.00 J0.06
Recv: echo:; Home offset:
Recv: echo:  M206 X0.00 Y0.00 Z0.00
Recv: echo:; Auto Bed Leveling:
Recv: echo:  M420 S1 Z0.00
Recv: echo:  G29 W I0 J0 Z-0.11525
Recv: echo:  G29 W I1 J0 Z-0.07275
Recv: echo:  G29 W I2 J0 Z0.00575
Recv: echo:  G29 W I3 J0 Z0.09325
Recv: echo:  G29 W I4 J0 Z0.23025
Recv: echo:  G29 W I0 J1 Z-0.13175
Recv: echo:  G29 W I1 J1 Z-0.07425
Recv: echo:  G29 W I2 J1 Z0.00000
Recv: echo:  G29 W I3 J1 Z0.10575
Recv: echo:  G29 W I4 J1 Z0.23850
Recv: echo:  G29 W I0 J2 Z-0.14250
Recv: echo:  G29 W I1 J2 Z-0.09650
Recv: echo:  G29 W I2 J2 Z-0.00525
Recv: echo:  G29 W I3 J2 Z0.08700
Recv: echo:  G29 W I4 J2 Z0.24350
Recv: echo:  G29 W I0 J3 Z-0.21525
Recv: echo:  G29 W I1 J3 Z-0.18675
Recv: echo:  G29 W I2 J3 Z-0.11350
Recv: echo:  G29 W I3 J3 Z-0.01775
Recv: echo:  G29 W I4 J3 Z0.16050
Recv: echo:  G29 W I0 J4 Z-0.28575
Recv: echo:  G29 W I1 J4 Z-0.27450
Recv: echo:  G29 W I2 J4 Z-0.22550
Recv: echo:  G29 W I3 J4 Z-0.12950
Recv: echo:  G29 W I4 J4 Z0.05675
Recv: echo:; PID settings:
Recv: echo:  M301 P14.72 I0.89 D61.22
Recv: echo:  M304 P690.34 I111.47 D1068.83
Recv: echo:; Retract: S<length> F<units/m> Z<lift>
Recv: echo:  M207 S3.00 W13.00 F2700.00 Z0.00
Recv: echo:; Recover: S<length> F<units/m>
Recv: echo:  M208 S0.00 W0.00 F480.00
Recv: echo:; Auto-Retract: S=0 to disable, 1 to interpret E-only moves as retract/recover
Recv: echo:  M209 S0
Recv: echo:; Z-Probe Offset (mm):
Recv: echo:  M851 X-41.00 Y-8.00 Z0.00
Recv: echo:; Stepper driver current:
Recv: echo:  M906 X730 Y730 Z850
Recv: echo:  M906 T0 E730
Recv: 
Recv: echo:; Hybrid Threshold:
Recv: echo:  M913 X152 Y152 Z10
Recv: echo:  M913 T0 E50
Recv: 
Recv: echo:; Driver stepping mode:
Recv: echo:  M569 S1 X Y Z
Recv: echo:; Linear Advance:
Recv: echo:  M900 K0.00
Recv: echo:; Filament load/unload lengths:
Recv: echo:  M603 L600.00 U75.00
Recv: echo:; Backlash compensation:
Recv: echo:  M425 F0.00 X0.00 Y0.00 Z0.00
Recv: echo:; Filament runout sensor:
Recv: echo:  M412 S1 D10.00
Recv: ok P15 B7
Recv:  T:26.22 /0.00 B:25.31 /0.00 @:0 B@:0
Recv: Not SD printing
Recv: wait


I did try to print but faced the exact same problem as before. 
When homing at the start of the print, the x and y homed properly, the head moved to the BLTouch to the center, Didn't deploy the BLTouch and started raising the bed until it would have crashed if not stopped.

**Comment by antoinelb1** [comment] 2020-06-15 00:49
HI guys, 

I did a little interesting test. 
When I start a print without any G28 command in the start Gcode, the printer works !!

Of course i had manually pushed a G28, G29 and M500 command before starting the print.

Interesting thing that happened before the successful print;
-Once i have had the printer reporting a probing fault at the first leveling of a G29 sequence. The printer then homed the X and Y went fo home Z but did not release the BL Touch... would have crashed. 
-After stopping a first successful print start ( to finetune z offset ) i have been surprise to see that the printer can no longer properly G28... did the same as it was doing when doing a G28 at print start.

**Comment by masc2279** [comment] 2020-06-15 01:10
Did you customize the firmware ?  So you say it works after removing G28 ? make sure you have 

#define RESTORE_LEVELING_AFTER_G28

in the firmware configuration.h enabled ...

**Comment by antoinelb1** [comment] 2020-06-15 22:53
Yes, i confirm that it works if i do not have the G28 command in my start Gcode, it is functional. 

I believe i only modified the minimum parameters to get it operational. 
I thought it could be something i change by mistake so i did build it 3 separate time, from different download, at different time, and ended-up with the same problem. 
Last download is about a month old...

I do have #define RESTORE_LEVELING_AFTER_G28 enabled in my current configuration.h

**Comment by InsanityAutomation** [comment] 2020-07-19 22:04
It sounds like a probe fault that isnt being detected by firmware. Im not sure theres much that can be done with it if the probe is faulting but not reporting the faulted state. Is the red light on it solid when or flashing when it fails to deploy?

**Comment by antoinelb1** [comment] 2020-09-04 23:05
No red light flashing.
As mentionned it really is like its going ot probe the bed but does not read the input...

It never happens when running the mesh through Octoprint.

**Comment by InsanityAutomation** [comment] 2021-04-28 15:45
Im going to close this old one, The issue is in areas outside where this project diverges from head, and utilizes a board that I dont have. There is a good chance its been resolved upstream and was included in subsequent builds.

**Closed as completed by InsanityAutomation** 2021-04-28 15:45 UTC
