### ISSUE TITLE
Babysteps issue

### ISSUE THREAD

**Issue by RS0ares** [InsanityAutomation/Marlin#194] opened 2021-04-29 00:17 UTC
Printer: CR10S Pro V2
Firmware: 10SProV2_50W_ET_DW7.3

 Today I installed a mosquito hotend with DDX PH4 300°C 24v 50W for CR-10(S)Pro/Max and i updated the firmware of my printer.

But I tried use the babysteps to level my bed, but the babysteps doesn't work correctly.

**Comment by Ericvf** [comment] 2021-04-29 08:42
I'm having an issue with Babystepping as well. See this issue:
https://github.com/InsanityAutomation/Marlin/issues/193

**Comment by InsanityAutomation** [comment] 2021-04-29 12:37
Closing as a duplicate of #193 however the bleeding branch should be resolved at the moment. Ill be generating more hex files after some more testing, and figuring out what @Ericvf is running into.

**Closed as completed by InsanityAutomation** 2021-04-29 12:37 UTC

**Comment by RS0ares** [comment] 2021-04-29 12:45
OK,I will wait for the hex files to update my printer.
👍

**Comment by InsanityAutomation** [comment] 2021-04-29 13:21
[10SProV2_50W_ET_DW7.3.1.hex.zip](https://github.com/InsanityAutomation/Marlin/files/6398835/10SProV2_50W_ET_DW7.3.1.hex.zip)

Give this a try

**Comment by Ericvf** [comment] 2021-04-29 14:15
What a champ! Can confirm babystepping is resolved for me now. 👍

**Comment by RS0ares** [comment] 2021-04-29 14:46
Later, I'll try the file, then I'll tell you how it was.
👍

**Comment by RS0ares** [comment] 2021-04-29 19:40
Thanks a lot mate!
It's working 😃
