### ISSUE TITLE
Display message error when doing Auto PID on CR-10S Pro

### ISSUE THREAD

**Issue by DaKrampus** [InsanityAutomation/Marlin#183] opened 2021-02-23 17:29 UTC
It existed in 7 so i checked if it would be gone in 7.2
Well its still there, btw this message pops up also (sometimes) after autolevel before setting the Z offset.

### Description ###
When going to settings -> tools -> PID tuning
I enter 200 degrees in the nozzlw pid window and press start.
After a while (pronterface shows its doing the auto tuning in the background) there comes a requester saying:

No filament, click yes to change filament or no to cancel
YES / NO

if I click yes, it goes back to the settings menu.

(in pronterface i can see the settings are stored)
(its logfile is the first I pasted below)

But if i say no, it goes into a print window, the head and the bed start moving... and somehow home in the 0 position.
now to be able to access any screen, i have to stop the print.. when i do so it stops it, and the head and the bed move again to the final position. (i still dont unterstand why this is done after every print, because the steppers are on and the bed is in the 0 position which means i have to switch off the printer every time i finishe printing in order to move the bed by hand and cleaning it a little bit. (but that is another issue)

### Steps to Reproduce ###

Easy, on a CR10S-Pro,  just do a PID autotune for the nozzle on the display 
I am using the BLTouch version of the 7.2 firmware all the rest is stock.

Here is the pronterface log for the first autotune...

***** Copy & Paste --- Start *******
toreSettings==
ManualSetTemp
  *******RTS_HandleData********
recdat.data[0] ==2
recdat.addr ==4188
== Checkkey==
21
toreSettings==
 ***recdat.data[0] =2
InLangChoice
Hotend PID
PID Autotune start
 bias: 94 d: 94 min: 197.27 max: 205.00
 bias: 91 d: 91 min: 197.27 max: 203.33
 bias: 90 d: 90 min: 197.59 max: 203.02 Ku: 42.16 Tu: 23.43
 Classic PID
 Kp: 25.30 Ki: 2.16 Kd: 74.09
 bias: 90 d: 90 min: 197.70 max: 202.78 Ku: 45.12 Tu: 23.43
 Classic PID
 Kp: 27.07 Ki: 2.31 Kd: 79.29
 bias: 90 d: 90 min: 197.59 max: 202.85 Ku: 43.55 Tu: 23.76
 Classic PID
 Kp: 26.13 Ki: 2.20 Kd: 77.60
 bias: 89 d: 89 min: 197.39 max: 202.78 Ku: 42.04 Tu: 23.43
 Classic PID
 Kp: 25.22 Ki: 2.15 Kd: 73.87
 bias: 90 d: 90 min: 197.27 max: 202.78 Ku: 41.63 Tu: 23.59
 Classic PID
 Kp: 24.98 Ki: 2.12 Kd: 73.67
 bias: 89 d: 89 min: 197.64 max: 202.78 Ku: 44.13 Tu: 23.27
 Classic PID
 Kp: 26.48 Ki: 2.28 Kd: 77.00
PID Autotune finished! Put the last Kp, Ki and Kd constants from below into Configuration.h
#define DEFAULT_Kp 26.48
#define DEFAULT_Ki 2.28
#define DEFAULT_Kd 77.00
==onUserConfirmRequired==
//action:prompt_end
//action:prompt_begin M1 Stop
//action:prompt_button Continue
//action:prompt_show
echo:busy: paused for user
echo:busy: paused for user
echo:busy: paused for user
echo:busy: paused for user
echo:busy: paused for user
echo:busy: paused for user
echo:busy: paused for user
echo:busy: paused for user
echo:busy: paused for user
echo:busy: paused for user
  *******RTS_HandleData********
recdat.data[0] ==1
recdat.addr ==4190
== Checkkey==
22
toreSettings==
 No Filament
Resume Yes during print
M876 Responding PROMPT_FILAMENT_RUNOUT_CONTINUE
ok P7 B1
***** Copy & Paste --- END *******

Now here ist the second logfile of the time afterwards where i said NO... 

***** Copy & Paste --- Start *******
PID Autotune finished! Put the last Kp, Ki and Kd constants from below into Configuration.h
#define DEFAULT_Kp 26.49
#define DEFAULT_Ki 2.33
#define DEFAULT_Kd 75.40
==onUserConfirmRequired==
//action:prompt_end
//action:prompt_begin M1 Stop
//action:prompt_button Continue
//action:prompt_show
echo:busy: paused for user
echo:busy: paused for user
echo:busy: paused for user
echo:busy: paused for user
echo:busy: paused for user
  *******RTS_HandleData********
recdat.data[0] ==0
recdat.addr ==4190
== Checkkey==
22
toreSettings==
 No Filament
 Filament Response No
Filament Stat 0 - 2
//action:cancel
//action:notification Print Aborted
ok P7 B0
==onConfigurationStoreWritten==
ok P7 B0
==onUserConfirmRequired==
//action:prompt_end
//action:prompt_begin M1 Stop
//action:prompt_button Continue
//action:prompt_show
echo:busy: paused for user
echo:busy: paused for user
echo:busy: paused for user
echo:busy: paused for user
  *******RTS_HandleData********
recdat.data[0] ==0
recdat.addr ==4190
== Checkkey==
22
toreSettings==
 No Filament
 Filament Response No
Filament Stat 0 - 2
//action:cancel
//action:notification Print Aborted
ok P7 B2
==onConfigurationStoreWritten==
ok P7 B4
  *******RTS_HandleData********
recdat.data[0] ==241
recdat.addr ==4104
== Checkkey==
3
toreSettings==
StopPrint
Stop Triggered241
//action:cancel
//action:notification Print Aborted
==onConfigurationStoreWritten==
ok P7 B4

***** Copy & Paste --- END *******

I tested the same thing on another printer a cr20 (with BLTouch) also with the 7.2 firmware..
There also is a requester coming saying click yes to confirm.. as long as you dont its stays idle.. if i click on the button, it then says settings stored.

I think  its just the wrong requester that is pulled up. (or there should be no requester at all.. -  just a line saying: settings stored.

Thats all from me (got other issues, but i am not sure they are bugs so i didnt include them here)

Keep up the great work 
Luc

PS: here a screenshot of the requester:
![bugrequester](https://user-images.githubusercontent.com/79415376/108882514-c57a3780-7604-11eb-989d-c78a6f2ae8ca.jpg)

Note the text is anyway wrong: "No filament" click yes to change filament.. 
(You cannot change something that is not there ;-)

**Comment by InsanityAutomation** [comment] 2021-04-27 03:42
This looks similar to an issue with pronterface sending M0 commands to machines at certain points. That would call the dialog. 
The steppers will disable themselves after a couple minutes however if you want to move it by hand sooner, under Settings you can disable the steppers immediately. I have not seen this reproduced without pronterface connected specifically, no other terminal causes this to my knowledge.

**Comment by DaKrampus** [comment] 2021-04-27 07:33
Sorry, I forgot to mention that i only hooked up pronterface after i had had the issue. So I do not think it is linked to pronterface. 
Maybe it did change some things in the background, but the main issue, having the filament change requester showing up on Auto PID is exactly the same.
To fix it for my usage, I now downgraded from the 7.2 version to 6.2 which does work fine. (Old things are not allways bad ;-)
Keep up the good work

Luc
PS: and no, i cannot disable the steppers because i cannot go to any other menu point once the requester is there.. even with pronterface because is keeps saying: echo:busy: paused for user

**Comment by InsanityAutomation** [comment] 2021-04-27 16:00
I ran through the PID tune a few more times this morning and didnt see this come up, can you check if 7.3 still exhibits this issue?

**Comment by DaKrampus** [comment] 2021-04-27 16:33
I will, but i am on a job assignment abroad and will only be back home on sunday evening.. I will check as quickly as possible on monday.. (sorry for the delay)

Luc

**Comment by InsanityAutomation** [comment] 2021-04-27 16:49
No rush, been away from this for awhile because of the chaos the pandemic brought to my every day life but trying to make sure everything that was left open is cleaned up at this point. Probably alot here I solved a long time ago but never touched base with anybody.

**Comment by tdcarter** [comment] 2021-05-24 15:05
Successfully did a PID auto-tune on my CR10sPro (v1) with the 7.3.1 update.

**Comment by InsanityAutomation** [comment] 2021-05-24 17:40
Sounds good! Between my testing and positive reports, ill close this. If there are still any issues just let me know and it can always be reopened.

**Closed as completed by InsanityAutomation** 2021-05-24 17:40 UTC
