### ISSUE TITLE
Creality_Bondtech // Ender6_BLT_DW7.4 // BLTouch not working

### ISSUE THREAD

**Issue by kathagor** [InsanityAutomation/Marlin#208] opened 2021-07-01 14:00 UTC
### Description

a) BLtouch is not working. When homing, the probe pin is deployed, the print head moves to the center position.
    On touch, the probe pin is not be retracted and the bed is moving further up, craching into the print head.

b) Button "Reset BLTouch"  in the tools menu is not working. When the button is pressed, the probe bin is not retracted.

Printer still stops, when the z-endstop is pushed.

### Steps to Reproduce

a1. Install firmware Ender6_BLT_DW7.4, display Firmware and a BLTouch must be insatalled.
a2. Home the printer oder start bed leveling. (warning, printer will not stop on hiting the probe pin!!)

b1. Deploy probe pin by hand.
b2. Press "Reset BLTouch" in the tools menu

**Expected behavior:** [What you expect to happen]

a)
- On touch, probe pin must be retracted and redeployed for second probing.
- Bed should stop on touch, travel down a bit and move up again for second probing attempt 

b)
- probe pin should be retracted

**Actual behavior:** [What actually happens]

a) Touch of the probe pin is not recognized. Bed will travel further up and crash into the nozzel.
b) nothing happens.

#### Additional Information

Video of BLtouch behavior

https://drive.google.com/file/d/1FwU9nqguGmtJi1O8hZQxQYSBxXUkuraM/view?usp=sharing

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by ubeyou** [comment] 2021-07-01 17:57
I believed same issue as this.

https://github.com/InsanityAutomation/Marlin/issues/207

they compiled the z stop version instead. 

By putting the 2 pin into z stop will solve the issue

**Comment by subhead** [comment] 2021-07-01 20:11
I have the same problem with my Ender 6 and BLTouch installed. Wiring the BLTouch as z stop does not solve this issue.

**Comment by InsanityAutomation** [comment] 2021-07-03 18:43
Closing as duplicate of prior issue. Please continue discussion in #207

**Closed as completed by InsanityAutomation** 2021-07-03 18:43 UTC
